import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from '@/app/Providers'
import { Props } from 'next/script'
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export async function generateMetadata() {
  const data = {
    title: 'Niezalogowany',
    description: 'Generated by create next app',
  }
  const cookie = cookies()

  const at = cookie.get('access_token')

  if (at) {
    data.title = 'Zalogowany'
  }

  return data
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
